### ISSUE TITLE
 The `libsass` binding was not found, current node version 4.0.0

### ISSUE THREAD

**Issue by epitaphmike** [jtangelder/sass-loader#162]
I am getting this error when using sass-loader. Current installed version of node is v4.0.0

I attempted to uninstall and reinstall node-sass with no avail.

Error: The `libsass` binding was not found in ../node_modules/node-sass/vendor/darwin-x64-11/binding.node
(STDERR) This usually happens because your node version has changed.
(STDERR) Run `npm rebuild node-sass` to build the binding for your current node version.
(STDERR)     at Object.sass.getBinaryPath (../node_modules/node-sass/lib/extensions.js:150:11)

**Comment by jorrit** [comment]
What's the output when you rebuild `node-sass`? Does it help when you remove your `node_modules` folder and run a fresh `npm install`?

**Comment by epitaphmike** [comment]
Output after running `npm rebuild node-sass`
> node-sass@3.3.3 install ../node_modules/node-sass
> node scripts/install.js

> node-sass@3.3.3 postinstall ../node_modules/node-sass
> node scripts/build.js

> ../node_modules/node-sass/vendor/darwin-x64-46/binding.node exists. testing binary.
> Binary is fine; exiting.
> node-sass@3.3.3 ../node_modules/node-sass

Wiping the `node_modules` folder and running `npm install` yields the same results unfortunately.

**Comment by jorrit** [comment]
The path is different: `darwin-x64-46` vs `darwin-x64-11`. Is anything in your code configuring this explicitly? Try searching for BINARY_PATH or binaryPath in your source code to find any instance.
The 11 or 46 is the value of `process.versions.modules`. This could also be a mismatch when you build `node-sass` with a different node version than you're running `sass-loader` with. You should check that too. It seems you're running it with a lower version than the one you're building it with.

**Comment by epitaphmike** [comment]
There is nothing explicitly pointing to `darwin-x64-11`, I blew out any global `node_sass` instances. I also loaded in manually the `darwin-x64-11/binding.node` just to test and started getting other errors related to LazyResult.async.

> ERROR in /meteor-webpack-react-kickstart/~/css-loader!/meteor-webpack-react-kickstart/~/sass-loader!/meteor-webpack-react-kickstart/react/todo/sass/Main.scss
> ? Module build failed: ReferenceError: Promise is not defined
> ? at LazyResult.async (/meteor-webpack-react-kickstart/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)

I added this package to [meteor-webpack-react-kickstart](https://github.com/thereactivestack/meteor-webpack-react-kickstart) if that helps. I also posted an issue on their repo to test against the actual environment in which I am using webpack.

I appreciate the help. Thank you.

**Comment by jorrit** [comment]
Are you absolutely sure that your program runs on node 4.0.0 and not some other version using nvm?

**Comment by epitaphmike** [comment]
Everything runs fine before I install sass-loader.

**Comment by jorrit** [comment]
That could be because you didn't use any modules that must be compiled before sass-loader/node-sass.

**Comment by sikanhe** [comment]
getting exactly same error here

**Comment by xor125** [comment]
+1

**Comment by epitaphmike** [comment]
There is a cross thread going [here](https://github.com/thereactivestack/kickstart/issues/6) as well. Seems it is a mac issue. I do not own a PC to confirm.

**Comment by xor125** [comment]
Just posted on the other thread. Can confirm this on PC win 8.1. Gonna try the win 10

**Comment by xx0r** [comment]
same for win 10

Error: The `libsass` binding was not found in .....\src\EmptyWebApplication\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-ia32-11\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (.....\src\EmptyWebApplication\node_modules\gulp-sass\node_modules\node-sass\lib\extensions.js:150:11)
    at Object.<anonymous> (.....\src\EmptyWebApplication\node_modules\gulp-sass\node_modules\node-sass\lib\index.js:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.....\src\EmptyWebApplication\node_modules\gulp-sass\index.js:163:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by sapox** [comment]
Same situation on Ubuntu 14.04. :-/

**Comment by jhnns** [comment]
I'm using node 4.1 on OSX and could not observe these kind of errors. Could you provide a minimal test setup that reproduces the error? Otherwise I doubt that this repository is the right location for this issue.

**Comment by xx0r** [comment]
I have checked out a clean version of the solution which lead to automated restore of the NPM packages to the latest version. Now the issue is happening no more... However, I tried to restore the packages before and it did not help.

**Comment by radotzki** [comment]
Quick fix: delete the node-sass folder from node_modules and run NPM install.
(OSX node version 4.1.2)

**Comment by natarajanmca11** [comment]
Thanks @radotzki 
Its working fine now. (Windows Node version 4.2.1 )

**Comment by jhnns** [comment]
Closing this for now because there is no example and it's probably not the right repository.

**Comment by haydenhancock** [comment]
Not sure if this should be closed as I am experiencing this same issue on Windows 10 and node 4.2.2.

**Comment by jhnns** [comment]
Do you have `node-sass` as `dependency` of your project? Since npm@3, `peerDependencies` won't be installed automatically anymore.

**Comment by haydenhancock** [comment]
In my devDependency, I have:

```javascript
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-sass": "^2.1.0",
    "node-sass": "^3.4.1"
  }
```

**Comment by haydenhancock** [comment]
I resolved by issue with Visual Studio by moving the PATH variable higher in priority as found [here](http://blog.boro2g.co.uk/grunt-and-gulp-tasks-in-visual-studio-2015-libsass-error/).

**Comment by jhnns** [comment]
Thx for sharing this!

**Comment by dontbesorry80** [comment]
Haydenhancock.
I have the same problem as this. But moving the PATH variable higher didn't solve the issue. However, I think my PATH variable seems very short... What's supposed to be be in there which helps?

**Comment by haydenhancock** [comment]
@dontbesorry80,

When you updated the path variable, did you sign out and back in? If not, try that. I'll send a screenshot of my setup when I can.

**Comment by dontbesorry80** [comment]
Never mind I got it sorted. I needed to add `C:\Users\robert\AppData\Roaming\npm` to my Path. Once that had been added and moved up in the list of priorities it has now been sorted.

**Comment by haydenhancock** [comment]
Awesome, Glad to here!

**Comment by lusse** [comment]
@haydenhancock  this solved my issue. Thanx a lot!
