### ISSUE TITLE
Webpack build hangs when compiling specific scss code

### ISSUE THREAD

**Issue by alexilyaev** [jtangelder/sass-loader#168]
I've created a test repo to demonstrate the issue:
https://github.com/alexilyaev/webpack-sass-bug

I'm not sure if the problem is with `sass-loader` or there's something with the `UglifyJsPlugin` that's hanging the build.

Would appreciate some guidance to where to repost this issue.
And perhaps how to strip it down to test `node-sass` without all the Webpack stuff.

**Comment by saper** [comment]
This can be https://github.com/sass/node-sass/issues/1048 which is also not easy to solve. I have prepared a workaround in https://github.com/sass/node-sass/issues/1112 - if you install that, all scripts will timeout after 2000 ms and the errors will be shown.

**Comment by alexilyaev** [comment]
Well, if that will be merged, I guess it's ok.
How do I install specifically that?

**Comment by saper** [comment]
> Well, if that will be merged, I guess it's ok.
> How do I install specifically that?

Checkout node-sass from git

m> git clone https://github.com/sass/node-sass
Cloning into 'node-sass'...
remote: Counting objects: 8241, done.
remote: Total 8241 (delta 0), reused 0 (delta 0), pack-reused 8241
Receiving objects: 100% (8241/8241), 14.48 MiB | 3.00 MiB/s, done.
Resolving deltas: 100% (4129/4129), done.
Checking connectivity... done.
m> cd node-sass
m> git fetch origin pull/1112/head
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 33 (delta 14), reused 0 (delta 0), pack-reused 4
Unpacking objects: 100% (33/33), done.
From https://github.com/sass/node-sass
 * branch            refs/pull/1112/head -> FETCH_HEAD
m> git merge FETCH_HEAD
Updating 9a46415..dbedf5f
Fast-forward
 binding.gyp                         |   1 +
 src/binding.cpp                     |  24 +++++++++++++++++--
 src/callback_bridge.h               | 108 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------
 src/custom_function_bridge.cpp      |   3 +++
 src/custom_function_bridge.h        |   1 +
 src/custom_importer_bridge.h        |   1 +
 src/debug.cpp                       |  29 ++++++++++++++++++++++
 src/debug.h                         |  37 ++++++++++++++++++++++++++++
 src/sass_types/sass_value_wrapper.h |  63 +++++++++++++++++++++++++++++++++++++++++++++++-
 9 files changed, 240 insertions(+), 27 deletions(-)
 create mode 100644 src/debug.cpp
 create mode 100644 src/debug.h

then

 npm install 

and you need to compile the code yourself:

 node script/build.js -f

The last step requires that you have python 2.x and a recent C++11 compiler installed.

**Comment by alexilyaev** [comment]
Ahm... I think I'll pass :-).

For now, I fixed my issue due to the wrong syntax in my scss code, but it will sure bite someone else.
Perhaps you can test it with my test-case repo above, and see if it actually throws the proper error after 2 seconds.

**Comment by saper** [comment]
Nope, this patch does not fix it. So it's still probably something else. With my patch applied even the original problem is relieved by the time out. Maybe it's not node-sass issue at all.

**Comment by saper** [comment]
Looking at the backtrace, this is definitely **not** a node-sass issue. Probably some some callbacks got deadlocked in webpack.

**Comment by alexilyaev** [comment]
Should I repost somewhere?

**Comment by saper** [comment]
I don't know, this bug is probably the right place to discuss this further.

**Comment by dmitry** [comment]
I guess it's related to this file: https://github.com/webpack/webpack/blob/7c5da6580733301295b30beca1aa0eb41b6881bf/lib/optimize/UglifyJsPlugin.js

**Comment by dmitry** [comment]
Looks like the `sourceMap` option might be an issue.

**Comment by dmitry** [comment]
Without this block of code it runs:

```

		compilation.plugin("normal-module-loader", function(context) {
			context.minimize = true;
		});
```

**Comment by dmitry** [comment]
Looks like css-loader requests https://github.com/ben-eb/cssnano, and then it hangs.

**Comment by dmitry** [comment]
The core issue is in the https://github.com/ben-eb/postcss-minify-selectors. If I comment this processor everything works again.

**Comment by dmitry** [comment]
Finally, it's related to: https://github.com/postcss/postcss-selector-parser, please use https://github.com/postcss/postcss-selector-parser/tree/master/src/__tests__ for prooving your bug.

**Comment by dmitry** [comment]
Hey guys, now it's solved with postcss-selector-parser 1.3.0

**Comment by alexilyaev** [comment]
So... we need to update the dependency in `postcss-minify-selectors` to `1.3.0`, then update in `cssnano` and then update here?

**Comment by dmitry** [comment]
I believe so.

**Comment by ccorcos** [comment]
having this same issue using `compass-mixins`...

**Comment by dmitry** [comment]
@ccorcos just upgrade to the latest `postcss-selector-parser` version.

**Comment by jhnns** [comment]
Self-solving issues are the best :+1:
